---
- name: Change hostname and Reboot
  hosts: "{{private_ip}}"
  gather_facts: false

  tasks: 
    - name: change hostname
      win_hostname:
        name: "{{name_tag}}"
      register: change_hostname

    - name: Reboot
      win_reboot:
      when: change_hostname.reboot_required
      register: reboot

    - name: debug
      debug:
        msg: "Hostname changed and Reboot"