---
- name: Domain join
  hosts: "{{private_ip}}"
  gather_facts: false

  tasks: 
    - name: Domain join
      win_domain_membership:
        dns_domain_name: "{{domain_name}}"
        domain_admin_user: "{{domain_user}}"
        domain_admin_password: "{{domain_passwd}}"
        state: domain
      register: domain_join

    - name: Reboot
      win_reboot:
      when: domain_join.reboot_required
      register: reboot

    - name: debug
      debug:
        msg: "Domain joined and Reboot"
      #when: reboot